### ISSUE TITLE
Ambiguous phrasing in question 9

### ISSUE THREAD

**Issue by kayleigh-greenwood** [jrosindell/HPC2021#2]
> "be careful to make sure that any new species really have a unique number assigned to them that has not been used before-try to think of a simple way to get a number to represent the new species that is different from any of the species numbers you have already"

In a community of 1, 2, 3, 4, 5 where we are creating a new species (6), do we need to consider whether species 6 has previously existed in previous iterations and instead use species 7? Or can we re-use the number of a species that has previously existed as long as it doesn't currently exist?

**Comment by jrosindell** [comment]
thanks - I've updated the questions and released a new file on teams
